import { prisma } from "@/lib/prisma";
import { Card, CardHeader } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { StatusBadge } from "@/components/ui/Badge";
import { formatOmr } from "@/lib/money";
import { formatDateTimeDMY } from "@/lib/date-format";
import { Prisma } from "@/generated/prisma/client";
import { hashStatementToken } from "@/lib/statement-token";

export const dynamic = "force-dynamic";

export default async function PublicStatementPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const now = new Date();
  const tokenHash = hashStatementToken(token);

  const customer = await prisma.customer.findFirst({
    where: {
      shareTokenExpires: { gt: now },
      OR: [{ shareToken: tokenHash }, { shareToken: token }],
    },
    include: {
      branch: true,
      debts: {
        where: { balanceAmount: { gt: new Prisma.Decimal(0) }, status: { in: ["OPEN", "PARTIALLY_PAID"] } },
        include: { invoice: { select: { invoiceNumber: true, createdAt: true } } },
        orderBy: { createdAt: "desc" },
      },
    },
  });

  if (!customer) {
    return (
      <main className="min-h-screen bg-app-bg p-6">
        <div className="mx-auto max-w-lg">
          <Card>
            <CardHeader title="Statement unavailable" description="This link is invalid or has expired. Please contact your supplier for a fresh statement." />
          </Card>
        </div>
      </main>
    );
  }

  const totalBalance = customer.debts.reduce((sum, d) => sum.add(d.balanceAmount), new Prisma.Decimal(0));

  return (
    <main className="min-h-screen bg-app-bg p-4 md:p-8">
      <div className="mx-auto max-w-screen-lg flex flex-col gap-6">
        <PageHeader
          eyebrow={customer.branch?.name ?? "NATIONAL INDUSTRIAL GAS PLANT - OMAN"}
          title={`Statement — ${customer.name}`}
          description={`Customer ${customer.customerNumber}. This is a read-only summary valid until ${formatDateTimeDMY(customer.shareTokenExpires!)}.`}
        />

        <Card>
          <CardHeader title="Outstanding Invoices" description={`Total balance owing: ${formatOmr(totalBalance)}`} />
          <div className="overflow-x-auto">
            <table className="ui-table">
              <thead>
                <tr>
                  <th>Invoice</th>
                  <th>Date</th>
                  <th>Original</th>
                  <th className="text-right">Paid</th>
                  <th className="text-right">Balance</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {customer.debts.map((debt) => {
                  const original = debt.originalAmount;
                  const paid = original.sub(debt.balanceAmount);
                  return (
                    <tr key={debt.id}>
                      <td className="is-strong">{debt.invoice.invoiceNumber}</td>
                      <td className="whitespace-nowrap">{formatDateTimeDMY(debt.invoice.createdAt)}</td>
                      <td className="num">{formatOmr(original)}</td>
                      <td className="num text-emerald-600">{formatOmr(paid)}</td>
                      <td className="num text-rose-600">{formatOmr(debt.balanceAmount)}</td>
                      <td><StatusBadge status={debt.status} /></td>
                    </tr>
                  );
                })}
                {customer.debts.length === 0 ? (
                  <tr>
                    <td className="px-4 py-10 text-center font-bold text-slate-500" colSpan={6}>
                      No outstanding balances.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </Card>

        <p className="text-center text-xs font-bold text-slate-400">
          Generated by the Sales &amp; Cylinder Tracking system · No authentication required for this shared link.
        </p>
      </div>
    </main>
  );
}
